import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const companies = sqliteTable(
  "companies",
  {
    id: text("id").primaryKey(),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    careersUrl: text("careers_url"),
    remotePolicyUrl: text("remote_policy_url"),
    priority: integer("priority").notNull().default(50),
    active: integer("active", { mode: "boolean" }).notNull().default(true),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (table) => [uniqueIndex("companies_slug_unique").on(table.slug)],
);

export const sources = sqliteTable("sources", {
  id: text("id").primaryKey(),
  companyId: text("company_id").notNull(),
  kind: text("kind").notNull(),
  url: text("url").notNull(),
  adapterKey: text("adapter_key"),
  configJson: text("config_json").notNull().default("{}"),
  browserRequired: integer("browser_required", { mode: "boolean" }).notNull().default(false),
  crawlIntervalMinutes: integer("crawl_interval_minutes").notNull().default(360),
  etag: text("etag"),
  lastModified: text("last_modified"),
  previousJobCount: integer("previous_job_count").notNull().default(0),
  consecutiveFailures: integer("consecutive_failures").notNull().default(0),
  lastSuccessAt: integer("last_success_at"),
  lastFailureAt: integer("last_failure_at"),
  nextDueAt: integer("next_due_at").notNull(),
  leaseOwner: text("lease_owner"),
  leaseUntil: integer("lease_until"),
  status: text("status").notNull().default("active"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const jobs = sqliteTable("jobs", {
  id: text("id").primaryKey(),
  sourceId: text("source_id").notNull(),
  companyId: text("company_id").notNull(),
  externalId: text("external_id").notNull(),
  dedupeKey: text("dedupe_key").notNull(),
  canonicalUrl: text("canonical_url").notNull(),
  title: text("title").notNull(),
  companyName: text("company_name").notNull(),
  department: text("department"),
  locationText: text("location_text"),
  employmentType: text("employment_type"),
  descriptionText: text("description_text").notNull(),
  searchText: text("search_text").notNull(),
  skillsText: text("skills_text").notNull().default(""),
  workplaceType: text("workplace_type").notNull().default("unknown"),
  remoteScope: text("remote_scope").notNull().default("unknown"),
  eligibleFromKorea: text("eligible_from_korea").notNull().default("unknown"),
  asyncLevel: text("async_level").notNull().default("unknown"),
  requiredTimezone: text("required_timezone"),
  requiredOverlapHours: real("required_overlap_hours"),
  salaryCurrency: text("salary_currency"),
  salaryMin: real("salary_min"),
  salaryMax: real("salary_max"),
  salaryInterval: text("salary_interval"),
  postedAt: integer("posted_at"),
  firstSeenAt: integer("first_seen_at").notNull(),
  lastSeenAt: integer("last_seen_at").notNull(),
  lastSeenRunId: text("last_seen_run_id"),
  missingCount: integer("missing_count").notNull().default(0),
  status: text("status").notNull().default("open"),
  closedAt: integer("closed_at"),
  score: integer("score").notNull().default(0),
  confidence: real("confidence").notNull().default(0),
  evidenceJson: text("evidence_json").notNull().default("[]"),
  contentHash: text("content_hash").notNull(),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});
